<a href="https://colab.research.google.com/github/Maria-Ul/Advanced-ML/blob/main/MNIST_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install scikit-learn==0.23.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
from sklearn.decomposition import PCA

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_pred, y_pred) = mnist.load_data()

In [ ]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [ ]:
np.array(X_train).shape

(60000, 28, 28)

In [ ]:
X_train_1 = np.reshape(X_train, (60000, 28*28))


In [ ]:
X_train_1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
pca = PCA()
pca.fit((X_train_1))

PCA()

In [ ]:
pca.explained_variance_ratio_[0:10]

array([0.09704664, 0.07095924, 0.06169089, 0.05389419, 0.04868797,
       0.04312231, 0.0327193 , 0.02883895, 0.02762029, 0.02357001])

In [ ]:
round(sum(pca.explained_variance_ratio_[0:52]),3)

0.831

In [ ]:
pca_52 = PCA(n_components=52, svd_solver='full').fit(X_train_1)

In [ ]:
fi = (pca_52.components_)

In [ ]:
Z = np.matmul(X_train_1, fi.transpose())

In [ ]:
X = pca_52.fit_transform(X_train_1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train_data, X_test_data, y_train_data, y_test_data = train_test_split(X, y_train, test_size=0.3, random_state=126)

In [ ]:
X_train_data

array([[ -862.79276576,  -432.90254845,   211.17682323, ...,
          -78.59161292,  -101.00322628,    30.96057856],
       [  434.37232834,  -233.59695721,   440.31196643, ...,
           28.49646963,   -93.89297308,  -196.97240804],
       [  277.56248323,  -100.03872835,   768.16443049, ...,
         -143.81169364,  -224.26955666,    96.69438228],
       ...,
       [ -352.94120868,  -254.43138971,   191.27295939, ...,
           29.51331114,  -184.81330987,    37.42329056],
       [-1024.52359401,  -426.48040747,   182.95383125, ...,
          -23.49087622,   -20.02274804,    32.45144759],
       [  394.9315425 ,  -299.93406295,   408.86212839, ...,
           34.48130057,    34.6701128 ,    60.59165172]])

In [ ]:
X_train_data.shape

(42000, 52)

In [ ]:
y_train_data

array([1, 2, 6, ..., 2, 1, 8], dtype=uint8)

In [ ]:
np.mean(X_train_data[:,0])

0.5965431171660774

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = OneVsRestClassifier(RandomForestClassifier(criterion='gini', min_samples_leaf=10, max_depth=20,n_estimators=10, random_state=126)).fit(X_train_data, y_train_data)

In [ ]:
pred = clf.predict(X_test_data)
count = 0
for i in range(len(pred)):
  if y_test_data[i]==5:
    if pred[i]==5:
      count+=1
print(count)

1414


In [ ]:
import pandas as pd
data = pd.read_csv('/content/pred_for_task.csv', index_col = 'FileName')

In [ ]:
data

Label  f0  f1  f2  f3  f4  f5  f6  f7  f8  ...  f774  f775  f776  \
FileName                                             ...                     
file1         7   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file2         2   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file3         1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file4         0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file5         4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file6         1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file7         4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file8         9   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file9         5   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file10        9   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file11        0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file12        6   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file13        9   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file14        0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file15        1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file16        5   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file17        9   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file18        7   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file19        3   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file20        4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file21        9   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file22        6   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file23        6   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file24        5   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file25        4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file26        0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file27        7   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file28        4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file29        0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file30        1   0   0   0   0   0   0   0   0   0  ...     0     0     0   

          f777  f778  f779  f780  f781  f782  f783  
FileName                                            
file1        0     0     0     0     0     0     0  
file2        0     0     0     0     0     0     0  
file3        0     0     0     0     0     0     0  
file4        0     0     0     0     0     0     0  
file5        0     0     0     0     0     0     0  
file6        0     0     0     0     0     0     0  
file7        0     0     0     0     0     0     0  
file8        0     0     0     0     0     0     0  
file9        0     0     0     0     0     0     0  
file10       0     0     0     0     0     0     0  
file11       0     0     0     0     0     0     0  
file12       0     0     0     0     0     0     0  
file13       0     0     0     0     0     0     0  
file14       0     0     0     0     0     0     0  
file15       0     0     0     0     0     0     0  
file16       0     0     0     0     0     0     0  
file17       0     0     0     0     0     0     0  
file18       0     0     0     0     0     0     0  
file19       0     0     0     0     0     0     0  
file20       0     0     0     0     0     0     0  
file21       0     0     0     0     0     0     0  
file22       0     0     0     0     0     0     0  
file23       0     0     0     0     0     0     0  
file24       0     0     0     0     0     0     0  
file25       0     0     0     0     0     0     0  
file26       0     0     0     0     0     0     0  
file27       0     0     0   

In [ ]:
label = data['Label']

In [ ]:
train_data = data.drop(['Label'], axis =1)

In [ ]:
train_data

f0  f1  f2  f3  f4  f5  f6  f7  f8  f9  ...  f774  f775  f776  f777  \
FileName                                          ...                           
file1      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file2      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file3      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file4      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file5      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file6      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file7      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file8      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file9      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file10     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file11     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file12     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file13     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file14     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file15     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file16     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file17     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file18     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file19     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file20     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file21     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file22     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file23     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file24     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file25     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file26     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file27     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file28     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file29     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
file30     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   

          f778  f779  f780  f781  f782  f783  
FileName                                      
file1        0     0     0     0     0     0  
file2        0     0     0     0     0     0  
file3        0     0     0     0     0     0  
file4        0     0     0     0     0     0  
file5        0     0     0     0     0     0  
file6        0     0     0     0     0     0  
file7        0     0     0     0     0     0  
file8        0     0     0     0     0     0  
file9        0     0     0     0     0     0  
file10       0     0     0     0     0     0  
file11       0     0     0     0     0     0  
file12       0     0     0     0     0     0  
file13       0     0     0     0     0     0  
file14       0     0     0     0     0     0  
file15       0     0     0     0     0     0  
file16       0     0     0     0     0     0  
file17       0     0     0     0     0     0  
file18       0     0     0     0     0     0  
file19       0     0     0     0     0     0  
file20       0     0     0     0     0     0  
file21       0     0     0     0     0     0  
file22       0     0     0     0     0     0  
file23       0     0     0     0     0     0  
file24       0     0     0     0     0     0  
file25       0     0     0     0     0     0  
file26       0     0     0     0     0     0  
file27       0     0     0     0     0     0  
file28       0     0     0     0     0     0  
file29 

In [ ]:
cut_data = pca_52.transform(train_data)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(


In [ ]:
pred = clf.predict_proba(cut_data[19].reshape(1, -1))

In [ ]:
pred

array([[1.01868589e-04, 0.00000000e+00, 6.57648478e-04, 1.21031788e-03,
        9.63210336e-01, 1.16939345e-04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.47028897e-02]])

In [ ]:
label[19]

4

In [ ]:
np.unique(label)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])