<a href="https://colab.research.google.com/github/Maria-Ul/Advanced-ML/blob/main/9_module_individual_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

Вам доступна таблица некоторых синтетических данных, на основании которых необходимо выполнить кластеризацию на K = 3 кластера методом К-средних.

In [ ]:
data = pd.read_csv('/content/Без названия.rtf', index_col = 'Object')

In [ ]:
data

X   Y  Cluster
Object                 
1        3  18        0
2       15  18        1
3       15   5        2
4       11   8        1
5        5  12        2
6        8   7        0
7       12  20        2
8       20   1        1
9        9   9        0
10       8  19        0
11      13   7        0
12      11  16        0
13      15  19        2
14      20   7        2
15      16  12        1

In [ ]:
X = data.drop(['Cluster'], axis = 1)

In [ ]:
X

X   Y
Object        
1        3  18
2       15  18
3       15   5
4       11   8
5        5  12
6        8   7
7       12  20
8       20   1
9        9   9
10       8  19
11      13   7
12      11  16
13      15  19
14      20   7
15      16  12

В sklearn используйте начальную инициализацию со следующими координатами центроидов и параметрами:

In [ ]:
kmeans = KMeans(n_clusters=3, init=np.array([[8.67, 12.67], [15.5, 9.75], [13.4, 12.6]]), max_iter=100, n_init=1)



In [ ]:
kmeans.fit(X)

KMeans(init=array([[ 8.67, 12.67],
       [15.5 ,  9.75],
       [13.4 , 12.6 ]]),
       max_iter=100, n_clusters=3, n_init=1)

Укажите, к какому кластеру будет отнесен тот или иной объект в результате кластеризации (задание засчитывается только в том случае, если все кластеры указаны верно).



In [ ]:
kmeans.labels_

array([0, 2, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1, 1], dtype=int32)

По результатам выполнения кластеризации определить среднее расстояний между объектами и центроидом, отнесенных к кластеру 0.


In [ ]:
kmeans.cluster_centers_

array([[ 6.25      , 11.5       ],
       [15.83333333,  6.66666667],
       [12.2       , 18.4       ]])

In [ ]:
cent0 = kmeans.cluster_centers_[0]

In [ ]:
cent0

array([ 6.25, 11.5 ])

In [ ]:
def d(x1,y1, x2,y2):
  return np.sqrt((x1-x2)**2+(y1-y2)**2)

In [ ]:
x_arr = np.array(X)

In [ ]:
x_arr

array([[ 3, 18],
       [15, 18],
       [15,  5],
       [11,  8],
       [ 5, 12],
       [ 8,  7],
       [12, 20],
       [20,  1],
       [ 9,  9],
       [ 8, 19],
       [13,  7],
       [11, 16],
       [15, 19],
       [20,  7],
       [16, 12]])

In [ ]:
count =0
sum = 0
for i, x in enumerate(x_arr):

  if kmeans.labels_[i]==0:
    print(x)
    sum+=d(x[0], x[1], cent0[0], cent0[1])
    count+=1
print(sum/count)

[ 3 18]
[ 5 12]
[8 7]
[9 9]
4.28958282361114
