<a href="https://colab.research.google.com/github/Maria-Ul/Advanced-ML/blob/main/Module_6_Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
t0 = -0.046
t1 = 0.541
t2 = -0.014
t3 = -0.132
z3 = 8
z1 = 4
z2 = 40
psi = t0+t1*z1+t2*z2+t3*z3
pplus = 1/(1+math.exp(-psi))
round(pplus,3)

0.623

гиперплоскость

In [ ]:
# 0 = a+bx1+cx2
a = -2.992
b =0.24
c = 1.102
x21 = 0
x11= -a/b
x22 = 1
x12 = -(a+c)/b

In [ ]:
round(1/(1+math.exp(-a)),3)

0.048

Индивидуальное задание

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/candy-data.csv', index_col = 'competitorname')

In [ ]:
data

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                              
100 Grand                      1       0        1               0       0   
3 Musketeers                   1       0        0               0       1   
One dime                       0       0        0               0       0   
One quarter                    0       0        0               0       0   
Air Heads                      0       1        0               0       0   
...                          ...     ...      ...             ...     ...   
Snickers Crisper               1       0        1               1       0   
Sour Patch Kids                0       1        0               0       0   
Sour Patch Tricksters          0       1        0               0       0   
Starburst                      0       1        0               0       0   
Strawberry bon bons            0       1        0               0       0   

                       crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                               
100 Grand                             1     0    1         0         0.732   
3 Musketeers                          0     0    1         0         0.604   
One dime                              0     0    0         0         0.011   
One quarter                           0     0    0         0         0.011   
Air Heads                             0     0    0         0         0.906   
...                                 ...   ...  ...       ...           ...   
Snickers Crisper                      1     0    1         0         0.604   
Sour Patch Kids                       0     0    0         1         0.069   
Sour Patch Tricksters                 0     0    0         1         0.069   
Starburst                             0     0    0         1         0.151   
Strawberry bon bons                   0     1    0         1         0.569   

                       pricepercent  winpercent  Y  
competitorname                                      
100 Grand                     0.860   66.971725  1  
3 Musketeers                  0.511   67.602936  1  
One dime                      0.116   32.261086  0  
One quarter                   0.511   46.116505  0  
Air Heads                     0.511   52.341465  1  
...                             ...         ... ..  
Snickers Crisper              0.651   59.529251  1  
Sour Patch Kids               0.116   59.863998  1  
Sour Patch Tricksters         0.116   52.825947  1  
Starburst                     0.220   67.037628  1  
Strawberry bon bons           0.058   34.578991  0  

[70 rows x 13 columns]

In [ ]:
train_set = data.drop(['Y', 'winpercent'], axis = 1)

In [ ]:
train_set = train_set.drop(index = ['Nestle Crunch','Skittles wildberry','Sour Patch Tricksters'])

In [ ]:
train_response = data.drop(index = ['Nestle Crunch','Skittles wildberry','Sour Patch Tricksters']).Y

In [ ]:
train_response

competitorname
100 Grand              1
3 Musketeers           1
One dime               0
One quarter            0
Air Heads              1
                      ..
Snickers               1
Snickers Crisper       1
Sour Patch Kids        1
Starburst              1
Strawberry bon bons    0
Name: Y, Length: 67, dtype: int64

In [ ]:
test = pd.read_csv('/content/candy-test.csv', index_col =  'competitorname').drop('Y', axis = 1)

In [ ]:
test

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                                  
Sugar Babies                       0       1        1               0       0   
Sugar Daddy                        1       0        0               0       1   
Super Bubble                       0       1        0               0       0   
Swedish Fish                       0       1        0               0       0   
Tootsie Pop                        1       0        0               0       0   
Tootsie Roll Juniors               1       0        0               0       0   
Tootsie Roll Midgies               1       0        0               0       0   
Tootsie Roll Snack Bars            1       0        0               0       0   
Trolli Sour Bites                  0       1        0               0       0   
Twix                               0       1        0               0       0   
Twizzlers                          0       1        0               0       0   
Warheads                           0       1        0               0       0   
Welchs Fruit Snacks                0       1        0               0       0   
Werthers Original Caramel          1       0        1               0       0   
Whoppers                           1       0        0               0       0   

                           crispedricewafer  hard  bar  pluribus  \
competitorname                                                     
Sugar Babies                              0     1    0         1   
Sugar Daddy                               0     1    0         0   
Super Bubble                              0     0    0         0   
Swedish Fish                              0     0    0         1   
Tootsie Pop                               0     0    0         0   
Tootsie Roll Juniors                      0     0    0         0   
Tootsie Roll Midgies                      0     0    0         1   
Tootsie Roll Snack Bars                   0     0    1         0   
Trolli Sour Bites                         0     0    0         1   
Twix                                      0     0    0         0   
Twizzlers                                 0     0    0         0   
Warheads                                  0     1    0         0   
Welchs Fruit Snacks                       0     0    0         1   
Werthers Original Caramel                 0     1    0         0   
Whoppers                                  0     0    0         1   

                           sugarpercent  pricepercent  
competitorname                                         
Sugar Babies                   0.647364       0.76700  
Sugar Daddy                    0.418000       0.32500  
Super Bubble                   0.162000       0.11600  
Swedish Fish                   0.604000       0.75500  
Tootsie Pop                    0.876560       0.56540  
Tootsie Roll Juniors           0.313000       0.51100  
Tootsie Roll Midgies           0.174000       0.01100  
Tootsie Roll Snack Bars        0.465000       0.32500  
Trolli Sour Bites              0.313000       0.25500  
Twix                           0.735430       0.86634  
Twizzlers                      0.220000       0.11600  
Warheads                       0.093000       0.11600  
Welchs Fruit Snacks            0.313000       0.31300  
Werthers Original Caramel      0.186000       0.26700  
Whoppers                       0.872000       0.84800

In [ ]:
test_response =  pd.read_csv('/content/candy-test.csv', index_col =  'competitorname').Y

In [ ]:
from sklearn.linear_model import LogisticRegression
random_state = 2019
solver = 'lbfgs'
clf = LogisticRegression(random_state = 2019, solver = 'lbfgs').fit(train_set, train_response)

In [ ]:
clf.classes_

array([0, 1])

In [ ]:
test1 = test.loc['Trolli Sour Bites']
test1 = np.array(test1).reshape(1,-1)
clf.predict_proba(test1)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[0.70832211, 0.29167789]])

In [ ]:
round(0.29167789,3)

0.292

In [ ]:
test1 = test.loc['Twizzlers']
test1 = np.array(test1).reshape(1,-1)
clf.predict_proba(test1)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[0.6962054, 0.3037946]])

In [ ]:
round(0.3037946,3)

0.304

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
y_pred = clf.predict(test)

In [ ]:
y_pred

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
confusion_matrix = confusion_matrix(test_response, y_pred)

In [ ]:
confusion_matrix

array([[7, 3],
       [2, 3]])

In [ ]:
TP = confusion_matrix[1][1]
TN = confusion_matrix[0][0]
FP = confusion_matrix[0][1]
FN = confusion_matrix[1][0]

In [ ]:
TPR = TP/(TP+FN)

In [ ]:
TPR

0.6

In [ ]:
presicion = TP/(TP+FP)

In [ ]:
presicion

0.5

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

roc_auc = roc_auc_score(test_response,clf.predict_proba(test)[:,1] ) # treshold = 0.5
fpr, tpr, thresholds = roc_curve(test_response,clf.predict_proba(test)[:,1])


# from sklearn.metrics import accuracy_score,  recall_score, roc_auc_score, precision_score

# THRESHOLD = 0.5
# preds = np.where(clf.predict_proba(test)[:, 1] > THRESHOLD, 1, 0)
# report2 = pd.DataFrame(data=[accuracy_score(test_response, preds), recall_score(test_response, preds),
#                              precision_score(test_response, preds), roc_auc_score(test_response, clf.predict_proba(test)[:, 1])],
#                        index=["accuracy", "recall", "precision", "roc_auc_score"])
# print("report2:\n", report2)
# print("\nAUC:")
# print(roc_auc_score(test_response, y_pred))
# print(roc_auc_score(test_response, preds))
# print(roc_auc_score(test_response, clf.predict_proba(test)[:,1]))

report2:
                       0
accuracy       0.666667
recall         0.600000
precision      0.500000
roc_auc_score  0.840000

AUC:
0.6499999999999999
0.6499999999999999
0.84


In [ ]:
round(0.6499999999999999,3)

0.65